import React, { createContext, useContext, useState, useEffect, ReactNode } from "react";

type Language = "es" | "en" | "pt";

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
  isLoaded: boolean;
}

const translations: Record<Language, Record<string, string>> = {
  es: {
    // Hero Section
    "hero.title": "Tu Información Médica,",
    "hero.titleHighlight": "Siempre Contigo",
    "hero.subtitle": "Accede a tu historial médico, alergias y contatos de emergencia en cualquier momento. Un código QR que puede salvar tu vida.",
    "hero.cta": "Crea tu Medical ID",
    "hero.viewCard": "Ver tu Medical Card",
    "hero.learnMore": "Conocer Más",

    // Problem Section
    "problem.title": "¿Te ha pasado esto?",
    "problem.item1": "Emergencias médicas en países extranjeros donde no hablas el idioma",
    "problem.item2": "Sin acceso a internet cuando más lo necesitas",
    "problem.item3": "Pérdida de tiempo crítico tratando de comunicar tu historial médico",

    // Solution Section
    "solution.title": "MedBridge es tu solución",
    "solution.item1": "Tarjeta médica digital segura con toda tu información",
    "solution.item2": "Funciona sin internet - acceso offline garantizado",
    "solution.item3": "Genera reportes médicos en PDF instantáneamente",
    "solution.item4": "Traducción automática a múltiples idiomas",

    // Access Section
    "access.title": "Acceso en Emergencias",
    "access.subtitle": "Diseñado para primeros auxilios. Escanea el QR y obtén información vital al instante, incluso sin conexión a internet.",
    "access.cta": "Crea tu Medical ID",
    "access.viewCard": "Ver tu Medical Card",

    // Features Section
    "features.title": "Características Principales",
    "features.subtitle": "Todo lo que necesitas para tu seguridad médica",
    "features.item1": "Perfil médico personal",
    "features.item2": "Tipo de sangre y alergias",
    "features.item3": "Contactos de emergencia",
    "features.item4": "Información del médico",
    "features.item5": "Tarjeta médica lista para emergencias",
    "features.item6": "Comparte reporte médico por email cuando lo necesites",

    // Privacy Section
    "privacy.title": "Tus datos permanecen privados.",
    "privacy.subtitle": "Tú decides quién ve tu información",
    "privacy.point1": "Sin almacenamiento en la nube",
    "privacy.point2": "Sin servidores",
    "privacy.point3": "Datos guardados localmente en tu dispositivo",
    "privacy.point4": "Tú controlas cuándo se comparte",

    // Form Steps
    "form.step": "Paso",
    "form.of": "de",
    
    // Form Sections
    "form.sections.personalInfo": "Información Personal",
    "form.sections.medicalHistory": "Historial Médico",
    "form.sections.emergencyContact": "Contacto de Emergencia",
    "form.sections.insurance": "Seguro Médico",
    "form.sections.additionalInfo": "Información Adicional",
    
    // Form Fields
    "form.fields.firstName": "Nombre",
    "form.fields.lastName": "Apellido",
    "form.fields.dateOfBirth": "Fecha de Nacimiento",
    "form.fields.gender": "Género",
    "form.fields.phoneNumber": "Teléfono",
    "form.fields.email": "Correo Electrónico",
    "form.fields.address": "Dirección",
    "form.fields.city": "Ciudad",
    "form.fields.state": "Estado/Provincia",
    "form.fields.zipCode": "Código Postal",
    "form.fields.country": "País",
    "form.fields.bloodType": "Tipo de Sangre",
    "form.fields.allergies": "Alergias",
    "form.fields.currentMedications": "Medicamentos Actuales",
    "form.fields.medicalConditions": "Condiciones Médicas",
    "form.fields.chronicIllnesses": "Enfermedades Crónicas",
    "form.fields.pastSurgeries": "Cirugías Previas",
    "form.fields.disabilities": "Discapacidades",
    "form.fields.emergencyContactName": "Nombre del Contacto",
    "form.fields.emergencyContactPhone": "Teléfono del Contacto",
    "form.fields.emergencyContactEmail": "Email del Contacto",
    "form.fields.emergencyContactRelationship": "Relación",
    "form.fields.insuranceProvider": "Proveedor de Seguro",
    "form.fields.policyNumber": "Número de Póliza",
    "form.fields.groupNumber": "Número de Grupo",
    "form.fields.insurancePhone": "Teléfono del Seguro",
    "form.fields.primaryPhysicianName": "Nombre del Médico",
    "form.fields.primaryPhysicianPhone": "Teléfono del Médico",
    "form.fields.primaryPhysicianClinic": "Clínica/Hospital",
    "form.fields.specialInstructions": "Instrucciones Especiales",
    "form.fields.additionalNotes": "Notas Adicionales",

    // Form Personal Information
    "form.personal.title": "Información Personal",
    "form.personal.fullName": "Nombre Completo",
    "form.personal.fullNamePlaceholder": "Ingresa tu nombre completo",
    "form.personal.dateOfBirth": "Fecha de Nacimiento",
    "form.personal.nationality": "Nacionalidad",
    "form.personal.nationalityPlaceholder": "Ingresa tu nacionalidad",
    "form.personal.gender": "Estado Civil",
    "form.personal.genderPlaceholder": "Selecciona estado civil",
    "form.personal.passportNumber": "Número de Pasaporte",
    "form.personal.passportNumberPlaceholder": "Ingresa número de pasaporte",
    "form.personal.address": "Dirección Permanente",
    "form.personal.addressPlaceholder": "Ingresa tu dirección",
    "form.personal.bloodType": "Tipo de Sangre",
    "form.personal.bloodTypePlaceholder": "Selecciona tu tipo de sangre",

    // Form Medical History
    "form.history.title": "Historial Médico",
    "form.history.chronicConditions": "Diagnósticos Previos",
    "form.history.chronicConditionsPlaceholder": "Ingresa diagnósticos previos",
    "form.history.currentMedications": "Medicamentos Actuales",
    "form.history.currentMedicationsPlaceholder": "Ingresa medicamentos actuales",
    "form.history.previousSurgeries": "Cirugías Previas",
    "form.history.previousSurgeriesPlaceholder": "Ingresa cirugías previas",
    "form.history.allergies": "Alergias a Medicamentos",
    "form.history.allergiesPlaceholder": "Ingresa alergias a medicamentos",

    // Form Emergency Contacts
    "form.emergency.title": "Contacto de Emergencia Principal",
    "form.emergency.name": "Nombre Completo",
    "form.emergency.namePlaceholder": "Ingresa nombre completo",
    "form.emergency.phone": "Teléfono Móvil",
    "form.emergency.phonePlaceholder": "Ingresa número de teléfono",
    "form.emergency.email": "Correo Electrónico",
    "form.emergency.emailPlaceholder": "Ingresa correo electrónico",

    // Form Insurance & Doctor
    "form.insurance.primaryPhysician": "Médico de Cabecera",
    "form.insurance.primaryPhysicianPlaceholder": "Nombre del médico",
    "form.insurance.physicianPhone": "Teléfono del Médico",
    "form.insurance.physicianPhonePlaceholder": "Teléfono del médico",

    // Form Additional
    "form.additional.advanceDirectives": "¿Acepta Transfusiones de Sangre?",

    // Common
    "common.optional": "(Opcional)",
    "common.yes": "Sí",
    "common.no": "No",
    "common.next": "Siguiente",
    "common.back": "Atrás",
    "common.unknown": "No especificado",
    "common.notes": "Notas",

    // Validation (Old keys kept for compatibility)
    "validation.required": "Este campo es obligatorio",
    "validation.invalidEmail": "Correo electrónico inválido",
    "validation.invalidPhone": "Número de teléfono inválido",
    "validation.invalidDate": "Fecha inválida",

    // Card
    "card.noProfile": "No hay perfil médico",
    "card.createProfilePrompt": "Crea tu perfil médico para acceder a tu tarjeta de emergencia",
    "card.createProfile": "Crear Perfil Médico",
    "card.name": "Nombre",
    "card.dob": "Fecha de Nacimiento",
    "card.bloodType": "Tipo de Sangre",
    "card.allergies": "Alergias",
    "card.currentMedications": "Medicamentos Actuales",
    "card.medicalConditions": "Condiciones Médicas",
    "card.current": "Actuales",
    "card.chronic": "Crónicas",
    "card.surgicalHistory": "Historial Quirúrgico",
    "card.emergencyContact": "Contacto de Emergencia",
    "card.primaryPhysician": "Médico de Cabecera",
    "card.specialInstructions": "Instrucciones Especiales",
    "card.additionalNotes": "Notas Adicionales",
    "card.phone": "Teléfono",
    "card.none": "Ninguna",
    "card.notSpecified": "No especificado",
    "card.editInfo": "Editar Información",
    "card.shareProfile": "Compartir Perfil Médico",
    "card.viewId": "Ver Identificación",
    "card.generating": "Generando...",
    "card.shareTitle": "Reporte Médico MedBridge",
    "card.shareText": "Información médica y de emergencia",
    "card.shareError": "Error al compartir. Por favor intenta de nuevo.",

    // ID Section
    "id.title": "Personal ID",
    "id.subtitle": "Sube una foto de tu identificación oficial",
    "id.uploadDocument": "Subir documento de identificación",
    "id.invalidFileType": "Por favor sube una imagen válida (JPG, PNG, etc.)",
    "id.fileTooLarge": "El archivo es muy grande. Máximo 3MB permitido.",
    "id.processingError": "Error al procesar la imagen. Intenta de nuevo.",
    "id.tapToUpload": "Toca para subir foto",
    "id.dragAndDrop": "o arrastra y suelta aquí",
    "id.useCamera": "Usar cámara",
    "id.chooseFromGallery": "Elegir de galería",
    "id.fileRequirements": "JPG, PNG hasta 3MB",
    "id.preview": "Vista previa",
    "id.remove": "Eliminar",
    "id.replacePhoto": "Cambiar foto",
    "id.save": "Guardar y continuar",
    "id.saveSuccess": "¡Foto guardada exitosamente!",
    "id.saveError": "Error al guardar la foto. Intenta de nuevo.",
    "id.note": "Nota",
    "id.noteDescription": "Esta foto se guarda localmente en tu dispositivo para verificación de identidad en emergencias.",

    // PDF
    "pdf.reportTitle": "Reporte Médico de Emergencia",
    "pdf.generatedOn": "Generado el",
    "pdf.language": "Idioma",
    "pdf.sectionPatient": "INFORMACIÓN DEL PACIENTE",
    "pdf.sectionMedicalBasics": "INFORMACIÓN MÉDICA BÁSICA",
    "pdf.sectionAllergies": "ALERGIAS",
    "pdf.sectionMedicalHistory": "HISTORIAL MÉDICO",
    "pdf.sectionEmergencyContact": "CONTACTO DE EMERGENCIA",
    "pdf.sectionPrimaryPhysician": "MÉDICO PRIMARIO",
    "pdf.fullName": "Nombre Completo",
    "pdf.dateOfBirth": "Fecha de Nacimiento",
    "pdf.nationality": "Nacionalidad",
    "pdf.bloodType": "Tipo de Sangre",
    "pdf.medicationAllergies": "Alergias a Medicamentos",
    "pdf.currentDiagnoses": "Diagnósticos Actuales",
    "pdf.previousDiagnoses": "Diagnósticos Previos",
    "pdf.currentMedications": "Medicamentos Actuales",
    "pdf.surgicalHistory": "Historial Quirúrgico",
    "pdf.contactName": "Nombre del Contacto",
    "pdf.mobilePhone": "Teléfono Móvil",
    "pdf.physicianName": "Nombre del Médico",
    "pdf.physicianPhone": "Teléfono del Médico",
    "pdf.clinicHospital": "Clínica/Hospital",
    "pdf.noneReported": "Ninguna reportada",
    "pdf.footerLine1": "Este documento fue generado localmente por el paciente.",
    "pdf.footerLine2": "Los datos médicos se almacenan offline en el dispositivo.",

    // NEW: Form step titles
    "form.steps.personalInfo": "Información Personal",
    "form.steps.emergencyContact": "Contacto de Emergencia",
    "form.steps.medicalInfo": "Información Médica",
    "form.steps.insurance": "Seguro Médico",
    "form.steps.primaryPhysician": "Doctor Primario",
    "form.steps.notesConsent": "Notas y Consentimiento",
    "form.steps.finalReview": "Revisión Final",

    // NEW: Form placeholders
    "form.placeholders.firstName": "Ej: Juan",
    "form.placeholders.lastName": "Ej: Pérez García",
    "form.placeholders.phone": "+1 234 567 8900",
    "form.placeholders.email": "ejemplo@correo.com",
    "form.placeholders.address": "Calle Principal #123",
    "form.placeholders.city": "Ciudad",
    "form.placeholders.state": "Estado",
    "form.placeholders.zipCode": "12345",
    "form.placeholders.country": "País",
    "form.placeholders.selectGender": "Seleccione su género",
    "form.placeholders.selectBloodType": "Seleccione tipo de sangre",
    "form.placeholders.selectRelationship": "Seleccione relación",
    "form.placeholders.fullName": "Nombre completo",
    "form.placeholders.insuranceProvider": "Nombre de la aseguradora",
    "form.placeholders.policyNumber": "Número de póliza",
    "form.placeholders.groupNumber": "Número de grupo",
    "form.placeholders.doctorName": "Dr. Juan Pérez",
    "form.placeholders.clinicName": "Nombre de la clínica o hospital",
    "form.placeholders.medicalConditions": "Describa cualquier condición médica actual",
    "form.placeholders.allergies": "Liste todas sus alergias (medicamentos, alimentos, etc.)",
    "form.placeholders.currentMedications": "Liste todos los medicamentos que toma actualmente",
    "form.placeholders.pastSurgeries": "Describa cualquier cirugía previa",
    "form.placeholders.chronicIllnesses": "Liste cualquier enfermedad crónica",
    "form.placeholders.disabilities": "Describa cualquier discapacidad",
    "form.placeholders.specialInstructions": "Cualquier instrucción especial para personal médico",
    "form.placeholders.additionalNotes": "Cualquier información adicional relevante",

    // NEW: Form consent
    "form.consent.title": "Consentimientos",
    "form.consent.treatment": "Consentimiento para Tratamiento",
    "form.consent.treatmentDesc": "Autorizo el tratamiento médico de emergencia",
    "form.consent.shareInfo": "Compartir Información Médica",
    "form.consent.shareInfoDesc": "Autorizo compartir mi información con personal médico",

    // NEW: Form review section
    "form.review.title": "Revisión Final",
    "form.review.subtitle": "Revise toda la información antes de guardar",
    "form.review.personalInfoSection": "Información Personal",
    "form.review.emergencyContactSection": "Contacto de Emergencia",
    "form.review.medicalInfoSection": "Información Médica",
    "form.review.insuranceSection": "Seguro y Doctor",
    "form.review.note": "Revise toda la información antes de guardar",

    // NEW: Form buttons
    "form.buttons.next": "Siguiente",
    "form.buttons.back": "Atrás",
    "form.buttons.save": "Guardar Perfil Médico",
    "form.buttons.addId": "Agregar Documento de Identificación",
    "form.buttons.addIdNote": "Opcional: Puede agregar una foto de su identificación",

    // NEW: Form genders
    "form.genders.male": "Masculino",
    "form.genders.female": "Femenino",
    "form.genders.other": "Otro",
    "form.genders.preferNotToSay": "Prefiero no decir",

    // NEW: Form relationships
    "form.relationships.spouse": "Esposo/a",
    "form.relationships.parent": "Padre/Madre",
    "form.relationships.child": "Hijo/a",
    "form.relationships.sibling": "Hermano/a",
    "form.relationships.friend": "Amigo/a",
    "form.relationships.other": "Otro",

    // NEW: Form validation
    "form.validation.required": "Este campo es requerido",
    "form.validation.minLength": "Debe tener al menos {min} caracteres",
    "form.validation.lettersOnly": "Solo letras permitidas",
    "form.validation.invalidEmail": "Email inválido",
    "form.validation.invalidPhone": "Teléfono inválido (mínimo 10 dígitos)",
    "form.validation.invalidDate": "Fecha inválida",

    // Legal - Terms & Conditions
    "legal.terms.title": "Términos y Condiciones",
    "legal.terms.version": "Versión 1.0",
    "legal.terms.lastUpdated": "Última Actualización: Enero 2024",
    "legal.terms.effectiveDate": "Fecha de Efectividad",
    "legal.terms.backButton": "Volver",
    "legal.terms.footer": "Al usar MedBridge, reconoces que has leído, entendido y aceptas estar vinculado a estos Términos y Condiciones.",
    "legal.terms.section1.title": "1. Aceptación de los Términos",
    "legal.terms.section1.content": "Al acceder y usar MedBridge, aceptas y te comprometes a cumplir estos Términos y Condiciones. Si no estás de acuerdo con estos términos, por favor no uses esta aplicación.",
    "legal.terms.section2.title": "2. Descripción del Servicio",
    "legal.terms.section2.content": "MedBridge es una herramienta de gestión de información médica personal que te permite almacenar y compartir tus datos médicos localmente en tu dispositivo. La aplicación genera reportes médicos y tarjetas de emergencia solo para uso personal.",
    "legal.terms.section3.title": "3. Sin Asesoramiento Médico",
    "legal.terms.section3.content": "MedBridge NO proporciona asesoramiento médico, diagnóstico o tratamiento. Esta aplicación es solo una herramienta informativa y no reemplaza la atención médica profesional. Siempre busca el consejo de proveedores de atención médica calificados con cualquier pregunta que puedas tener sobre condiciones médicas.",
    "legal.terms.section4.title": "4. Solo Uso Personal",
    "legal.terms.section4.content": "Esta aplicación está destinada solo para uso personal y no comercial. No puedes usar MedBridge para ningún propósito comercial o de ninguna manera que viole leyes o regulaciones aplicables.",
    "legal.terms.section5.title": "5. Responsabilidad del Usuario",
    "legal.terms.section5.content": "Eres el único responsable de la precisión e integridad de la información médica que ingresas en MedBridge. También eres responsable de determinar cuándo y con quién compartir tu información médica. Recomendamos encarecidamente revisar tu información regularmente y mantenerla actualizada.",
    "legal.terms.section6.title": "6. Almacenamiento de Datos",
    "legal.terms.section6.content": "Tus datos médicos se almacenan localmente en tu dispositivo. Solo las fotos de identificación pueden subirse a almacenamiento seguro en la nube. Eres responsable de hacer respaldo de tus datos y mantener la seguridad de tu dispositivo.",
    "legal.terms.section7.title": "7. Limitación de Responsabilidad",
    "legal.terms.section7.content": "MedBridge se proporciona 'tal cual' sin garantías, expresas o implícitas. No seremos responsables de ningún daño derivado del uso o la incapacidad de usar esta aplicación, incluyendo pero no limitado a daños directos, indirectos, incidentales o consecuentes.",
    "legal.terms.section8.title": "8. Sin Garantía de Precisión",
    "legal.terms.section8.content": "No garantizamos que la aplicación esté libre de errores, ininterrumpida o libre de virus u otros componentes dañinos. No somos responsables de errores u omisiones en el contenido que creas o almacenas.",
    "legal.terms.section9.title": "9. Uso en Emergencias",
    "legal.terms.section9.content": "Aunque MedBridge está diseñado para facilitar el acceso a información médica de emergencia, no podemos garantizar que los respondedores de emergencia puedan acceder o confiar en la información almacenada en la aplicación. Siempre lleva formas tradicionales de identificación médica como respaldo.",
    "legal.terms.section10.title": "10. Modificaciones a los Términos",
    "legal.terms.section10.content": "Nos reservamos el derecho de modificar estos Términos y Condiciones en cualquier momento. Cuando hagamos cambios, actualizaremos el número de versión y la fecha de efectividad. El uso continuado de la aplicación después de los cambios constituye la aceptación de los nuevos términos.",
    "legal.terms.section11.title": "11. Terminación",
    "legal.terms.section11.content": "Puedes dejar de usar MedBridge en cualquier momento. Simplemente elimina la aplicación y cualquier dato asociado de tu dispositivo. Estos Términos y Condiciones continuarán aplicándose a cualquier uso que hayas hecho de la aplicación antes de la terminación.",
    "legal.terms.section12.title": "12. Ley Aplicable",
    "legal.terms.section12.content": "Estos Términos y Condiciones se regirán e interpretarán de acuerdo con las leyes locales aplicables, sin tener en cuenta los principios de conflicto de leyes.",
    "legal.terms.section13.title": "13. Contacto",
    "legal.terms.section13.content": "Si tienes alguna pregunta sobre estos Términos y Condiciones, por favor contáctanos a través de los canales de soporte de la aplicación.",

    // Legal - Privacy Policy
    "legal.privacy.title": "Política de Privacidad",
    "legal.privacy.version": "Versión 1.0",
    "legal.privacy.lastUpdated": "Última Actualización: Enero 2024",
    "legal.privacy.effectiveDate": "Fecha de Efectividad",
    "legal.privacy.backButton": "Volver",
    "legal.privacy.footer": "Al usar MedBridge, reconoces que has leído, entendido y aceptas esta Política de Privacidad.",
    "legal.privacy.section1.title": "1. Introducción",
    "legal.privacy.section1.content": "Esta Política de Privacidad explica cómo MedBridge maneja tu información personal y médica. Estamos comprometidos a proteger tu privacidad y darte control sobre tus datos.",
    "legal.privacy.section2.title": "2. Información que Recopilamos",
    "legal.privacy.section2.content": "MedBridge te permite almacenar información personal y médica incluyendo: nombre, fecha de nacimiento, historial médico, medicamentos, alergias, contactos de emergencia y fotos de identificación. Esta información es ingresada voluntariamente por ti.",
    "legal.privacy.section3.title": "3. Cómo Almacenamos Tus Datos",
    "legal.privacy.section3.content": "Tus datos médicos se almacenan localmente en tu dispositivo usando mecanismos de almacenamiento del navegador. NO almacenamos tu información médica en nuestros servidores o en la nube. Solo las fotos de identificación pueden subirse a almacenamiento seguro en la nube para fines de respaldo.",
    "legal.privacy.section4.title": "4. Sin Almacenamiento en la Nube de Datos Médicos",
    "legal.privacy.section4.content": "Tu información médica (diagnósticos, medicamentos, alergias, etc.) nunca sale de tu dispositivo. No se transmite a ningún servidor, servicio en la nube o tercero. Estos datos existen solo en tu dispositivo local.",
    "legal.privacy.section5.title": "5. Fotos de Identificación",
    "legal.privacy.section5.content": "Si eliges subir una foto de identificación, puede almacenarse en almacenamiento seguro en la nube. Esto es opcional y solo para el propósito de verificación de identidad en situaciones de emergencia.",
    "legal.privacy.section6.title": "6. Sin Analytics o Rastreo",
    "legal.privacy.section6.content": "NO rastreamos, analizamos o monitoreamos el uso de tus datos médicos. No usamos cookies, servicios de analytics o píxeles de rastreo para recopilar información sobre cómo usas tu información médica.",
    "legal.privacy.section7.title": "7. Sin Venta o Compartir",
    "legal.privacy.section7.content": "NUNCA venderemos, alquilaremos o compartiremos tu información personal o médica con terceros para fines de marketing o comerciales. Tus datos son tuyos y solo tuyos.",
    "legal.privacy.section8.title": "8. Control del Usuario",
    "legal.privacy.section8.content": "Tienes control completo sobre tus datos. Puedes editar, eliminar o exportar tu información en cualquier momento. Como los datos se almacenan localmente, eliminar la aplicación o limpiar los datos del navegador eliminará permanentemente tu información.",
    "legal.privacy.section9.title": "9. Seguridad de Datos",
    "legal.privacy.section9.content": "Aunque implementamos medidas de seguridad, la seguridad de tus datos depende en última instancia de la seguridad de tu dispositivo. Recomendamos: usar contraseñas en el dispositivo, habilitar cifrado, mantener tu dispositivo actualizado y tener cuidado sobre quién tiene acceso físico a tu dispositivo.",
    "legal.privacy.section10.title": "10. Servicios de Terceros",
    "legal.privacy.section10.content": "MedBridge puede usar servicios de terceros para almacenamiento en la nube de fotos de identificación. Estos servicios tienen sus propias políticas de privacidad. Elegimos proveedores respetables y limitamos el intercambio de datos solo a lo necesario.",
    "legal.privacy.section11.title": "11. Privacidad de Menores",
    "legal.privacy.section11.content": "MedBridge puede usarse para almacenar información médica de usuarios de todas las edades, incluidos menores. Los padres o tutores legales son responsables de gestionar la información médica de menores.",
    "legal.privacy.section12.title": "12. Cambios a la Política de Privacidad",
    "legal.privacy.section12.content": "Podemos actualizar esta Política de Privacidad de vez en cuando. Cuando lo hagamos, actualizaremos el número de versión y la fecha de efectividad. El uso continuado de la aplicación constituye la aceptación de la política actualizada.",
    "legal.privacy.section13.title": "13. Tus Derechos",
    "legal.privacy.section13.content": "Tienes derecho a: acceder a tus datos, corregir datos inexactos, eliminar tus datos, exportar tus datos y controlar quién ve tu información. Todas estas acciones pueden realizarse directamente dentro de la aplicación.",
    "legal.privacy.section14.title": "14. Contacto",
    "legal.privacy.section14.content": "Si tienes preguntas sobre esta Política de Privacidad o cómo manejamos tu información, por favor contáctanos a través de los canales de soporte de la aplicación.",

    // Legal Acceptance Modal
    "legal.modal.title": "Aviso de Términos y Privacidad",
    "legal.modal.description": "Se requiere aceptación legal para usar la aplicación",
    "legal.modal.summary1": "Esta aplicación te permite almacenar y compartir información médica solo para uso personal.",
    "legal.modal.summary2": "Tus datos médicos se almacenan localmente en tu dispositivo. Solo una foto de identificación puede subirse a almacenamiento seguro en la nube.",
    "legal.modal.summary3": "Esta aplicación no proporciona asesoramiento médico y no reemplaza la atención médica profesional.",
    "legal.modal.readTerms": "Leer Términos y Condiciones",
    "legal.modal.readPrivacy": "Leer Política de Privacidad",
    "legal.modal.checkbox": "He leído y acepto los Términos y Condiciones y la Política de Privacidad",
    "legal.modal.acceptButton": "Aceptar y Continuar",
    "legal.modal.accept": "Aceptar y Continuar",
    "legal.modal.back": "Volver"
  },
  en: {
    // Hero Section
    "hero.title": "Your Medical Information,",
    "hero.titleHighlight": "Always With You",
    "hero.subtitle": "Access your medical history, allergies, and emergency contacts anytime. A QR code that can save your life.",
    "hero.cta": "Create Your Medical ID",
    "hero.viewCard": "View Your Medical Card",
    "hero.learnMore": "Learn More",

    // Problem Section
    "problem.title": "Has this happened to you?",
    "problem.item1": "Medical emergencies in foreign countries where you don't speak the language",
    "problem.item2": "No internet access when you need it most",
    "problem.item3": "Wasting critical time trying to communicate your medical history",

    // Solution Section
    "solution.title": "MedBridge is your solution",
    "solution.item1": "Secure digital medical card with all your information",
    "solution.item2": "Works without internet - guaranteed offline access",
    "solution.item3": "Generate medical reports in PDF instantly",
    "solution.item4": "Automatic translation to multiple languages",

    // Access Section
    "access.title": "Emergency Access",
    "access.subtitle": "Designed for first responders. Scan the QR and get vital information instantly, even offline.",
    "access.cta": "Create Your Medical ID",
    "access.viewCard": "View Your Medical Card",

    // Features Section
    "features.title": "Key Features",
    "features.subtitle": "Everything you need for your medical safety",
    "features.item1": "Personal medical profile",
    "features.item2": "Blood type and allergies",
    "features.item3": "Emergency contacts",
    "features.item4": "Doctor information",
    "features.item5": "Medical card ready for emergencies",
    "features.item6": "Share medical report by email when needed",

    // Privacy Section
    "privacy.title": "Your data stays private.",
    "privacy.subtitle": "You decide who sees your information",
    "privacy.point1": "No cloud storage",
    "privacy.point2": "No servers",
    "privacy.point3": "Data saved locally on your device",
    "privacy.point4": "You control when it's shared",

    // Form Steps
    "form.step": "Step",
    "form.of": "of",
    
    // Form Sections
    "form.sections.personalInfo": "Personal Information",
    "form.sections.medicalHistory": "Medical History",
    "form.sections.emergencyContact": "Emergency Contact",
    "form.sections.insurance": "Medical Insurance",
    "form.sections.additionalInfo": "Additional Information",
    
    // Form Fields
    "form.fields.firstName": "First Name",
    "form.fields.lastName": "Last Name",
    "form.fields.dateOfBirth": "Date of Birth",
    "form.fields.gender": "Gender",
    "form.fields.phoneNumber": "Phone Number",
    "form.fields.email": "Email",
    "form.fields.address": "Address",
    "form.fields.city": "City",
    "form.fields.state": "State/Province",
    "form.fields.zipCode": "ZIP Code",
    "form.fields.country": "Country",
    "form.fields.bloodType": "Blood Type",
    "form.fields.allergies": "Allergies",
    "form.fields.currentMedications": "Current Medications",
    "form.fields.medicalConditions": "Medical Conditions",
    "form.fields.chronicIllnesses": "Chronic Illnesses",
    "form.fields.pastSurgeries": "Past Surgeries",
    "form.fields.disabilities": "Disabilities",
    "form.fields.emergencyContactName": "Contact Name",
    "form.fields.emergencyContactPhone": "Contact Phone",
    "form.fields.emergencyContactEmail": "Contact Email",
    "form.fields.emergencyContactRelationship": "Relationship",
    "form.fields.insuranceProvider": "Insurance Provider",
    "form.fields.policyNumber": "Policy Number",
    "form.fields.groupNumber": "Group Number",
    "form.fields.insurancePhone": "Insurance Phone",
    "form.fields.primaryPhysicianName": "Physician Name",
    "form.fields.primaryPhysicianPhone": "Physician Phone",
    "form.fields.primaryPhysicianClinic": "Clinic/Hospital",
    "form.fields.specialInstructions": "Special Instructions",
    "form.fields.additionalNotes": "Additional Notes",

    // Form Personal Information
    "form.personal.title": "Personal Information",
    "form.personal.fullName": "Full Name",
    "form.personal.fullNamePlaceholder": "Enter your full name",
    "form.personal.dateOfBirth": "Date of Birth",
    "form.personal.nationality": "Nationality",
    "form.personal.nationalityPlaceholder": "Enter your nationality",
    "form.personal.gender": "Marital Status",
    "form.personal.genderPlaceholder": "Select marital status",
    "form.personal.passportNumber": "Passport Number",
    "form.personal.passportNumberPlaceholder": "Enter passport number",
    "form.personal.address": "Permanent Address",
    "form.personal.addressPlaceholder": "Enter your address",
    "form.personal.bloodType": "Blood Type",
    "form.personal.bloodTypePlaceholder": "Select your blood type",

    // Form Medical History
    "form.history.title": "Medical History",
    "form.history.chronicConditions": "Previous Diagnoses",
    "form.history.chronicConditionsPlaceholder": "Enter previous diagnoses",
    "form.history.currentMedications": "Current Medications",
    "form.history.currentMedicationsPlaceholder": "Enter current medications",
    "form.history.previousSurgeries": "Previous Surgeries",
    "form.history.previousSurgeriesPlaceholder": "Enter previous surgeries",
    "form.history.allergies": "Medication Allergies",
    "form.history.allergiesPlaceholder": "Enter medication allergies",

    // Form Emergency Contacts
    "form.emergency.title": "Primary Emergency Contact",
    "form.emergency.name": "Full Name",
    "form.emergency.namePlaceholder": "Enter full name",
    "form.emergency.phone": "Mobile Phone",
    "form.emergency.phonePlaceholder": "Enter phone number",
    "form.emergency.email": "Email",
    "form.emergency.emailPlaceholder": "Enter email",

    // Form Insurance & Doctor
    "form.insurance.primaryPhysician": "Primary Physician",
    "form.insurance.primaryPhysicianPlaceholder": "Doctor's name",
    "form.insurance.physicianPhone": "Physician Phone",
    "form.insurance.physicianPhonePlaceholder": "Doctor's phone",

    // Form Additional
    "form.additional.advanceDirectives": "Accepts Blood Transfusions?",

    // Common
    "common.optional": "(Optional)",
    "common.yes": "Yes",
    "common.no": "No",
    "common.next": "Next",
    "common.back": "Back",
    "common.unknown": "Not specified",
    "common.notes": "Notes",

    // Validation
    "validation.required": "This field is required",
    "validation.invalidEmail": "Invalid email",
    "validation.invalidPhone": "Invalid phone number",
    "validation.invalidDate": "Invalid date",

    // Card
    "card.noProfile": "No Medical Profile",
    "card.createProfilePrompt": "Create your medical profile to access your emergency card",
    "card.createProfile": "Create Medical Profile",
    "card.name": "Name",
    "card.dob": "Date of Birth",
    "card.bloodType": "Blood Type",
    "card.allergies": "Allergies",
    "card.currentMedications": "Current Medications",
    "card.medicalConditions": "Medical Conditions",
    "card.current": "Current",
    "card.chronic": "Chronic",
    "card.surgicalHistory": "Surgical History",
    "card.emergencyContact": "Emergency Contact",
    "card.primaryPhysician": "Primary Physician",
    "card.specialInstructions": "Special Instructions",
    "card.additionalNotes": "Additional Notes",
    "card.phone": "Phone",
    "card.none": "None",
    "card.notSpecified": "Not specified",
    "card.editInfo": "Edit Information",
    "card.shareProfile": "Share Medical Profile",
    "card.viewId": "View Identification",
    "card.generating": "Generating...",
    "card.shareTitle": "MedBridge Medical Report",
    "card.shareText": "Medical profile and emergency information",
    "card.shareError": "Error sharing medical profile. Please try again.",

    // ID Section
    "id.title": "Personal ID",
    "id.subtitle": "Upload a photo of your official identification",
    "id.uploadDocument": "Upload identification document",
    "id.invalidFileType": "Please upload a valid image (JPG, PNG, etc.)",
    "id.fileTooLarge": "File is too large. Maximum 3MB allowed.",
    "id.processingError": "Error processing image. Please try again.",
    "id.tapToUpload": "Tap to upload photo",
    "id.dragAndDrop": "or drag and drop here",
    "id.useCamera": "Use camera",
    "id.chooseFromGallery": "Choose from gallery",
    "id.fileRequirements": "JPG, PNG up to 3MB",
    "id.preview": "Preview",
    "id.remove": "Remove",
    "id.replacePhoto": "Replace photo",
    "id.save": "Save and continue",
    "id.saveSuccess": "Photo saved successfully!",
    "id.saveError": "Error saving photo. Please try again.",
    "id.note": "Note",
    "id.noteDescription": "This photo is stored locally on your device for identity verification in emergencies.",

    // PDF
    "pdf.reportTitle": "Emergency Medical Report",
    "pdf.generatedOn": "Generated on",
    "pdf.language": "Language",
    "pdf.sectionPatient": "PATIENT INFORMATION",
    "pdf.sectionMedicalBasics": "BASIC MEDICAL INFORMATION",
    "pdf.sectionAllergies": "ALLERGIES",
    "pdf.sectionMedicalHistory": "MEDICAL HISTORY",
    "pdf.sectionEmergencyContact": "EMERGENCY CONTACT",
    "pdf.sectionPrimaryPhysician": "PRIMARY PHYSICIAN",
    "pdf.fullName": "Full Name",
    "pdf.dateOfBirth": "Date of Birth",
    "pdf.nationality": "Nationality",
    "pdf.bloodType": "Blood Type",
    "pdf.medicationAllergies": "Medication Allergies",
    "pdf.currentDiagnoses": "Current Diagnoses",
    "pdf.previousDiagnoses": "Previous Diagnoses",
    "pdf.currentMedications": "Current Medications",
    "pdf.surgicalHistory": "Surgical History",
    "pdf.contactName": "Contact Name",
    "pdf.mobilePhone": "Mobile Phone",
    "pdf.physicianName": "Physician Name",
    "pdf.physicianPhone": "Physician Phone",
    "pdf.clinicHospital": "Clinic/Hospital",
    "pdf.noneReported": "None reported",
    "pdf.footerLine1": "This document was generated locally by the patient.",
    "pdf.footerLine2": "Medical data is stored offline on the device.",

    // NEW: Form step titles
    "form.steps.personalInfo": "Personal Information",
    "form.steps.emergencyContact": "Emergency Contact",
    "form.steps.medicalInfo": "Medical Information",
    "form.steps.insurance": "Medical Insurance",
    "form.steps.primaryPhysician": "Primary Physician",
    "form.steps.notesConsent": "Notes and Consent",
    "form.steps.finalReview": "Final Review",

    // NEW: Form placeholders
    "form.placeholders.firstName": "e.g., John",
    "form.placeholders.lastName": "e.g., Smith",
    "form.placeholders.phone": "+1 234 567 8900",
    "form.placeholders.email": "example@email.com",
    "form.placeholders.address": "123 Main Street",
    "form.placeholders.city": "City",
    "form.placeholders.state": "State",
    "form.placeholders.zipCode": "12345",
    "form.placeholders.country": "Country",
    "form.placeholders.selectGender": "Select your gender",
    "form.placeholders.selectBloodType": "Select blood type",
    "form.placeholders.selectRelationship": "Select relationship",
    "form.placeholders.fullName": "Full name",
    "form.placeholders.insuranceProvider": "Insurance provider name",
    "form.placeholders.policyNumber": "Policy number",
    "form.placeholders.groupNumber": "Group number",
    "form.placeholders.doctorName": "Dr. John Smith",
    "form.placeholders.clinicName": "Clinic or hospital name",
    "form.placeholders.medicalConditions": "Describe any current medical conditions",
    "form.placeholders.allergies": "List all your allergies (medications, foods, etc.)",
    "form.placeholders.currentMedications": "List all medications you are currently taking",
    "form.placeholders.pastSurgeries": "Describe any previous surgeries",
    "form.placeholders.chronicIllnesses": "List any chronic illnesses",
    "form.placeholders.disabilities": "Describe any disabilities",
    "form.placeholders.specialInstructions": "Any special instructions for medical personnel",
    "form.placeholders.additionalNotes": "Any additional relevant information",

    // NEW: Form consent
    "form.consent.title": "Consents",
    "form.consent.treatment": "Consent for Treatment",
    "form.consent.treatmentDesc": "I authorize emergency medical treatment",
    "form.consent.shareInfo": "Share Medical Information",
    "form.consent.shareInfoDesc": "I authorize sharing my information with medical personnel",

    // NEW: Form review section
    "form.review.title": "Final Review",
    "form.review.subtitle": "Review all information before saving",
    "form.review.personalInfoSection": "Personal Information",
    "form.review.emergencyContactSection": "Emergency Contact",
    "form.review.medicalInfoSection": "Medical Information",
    "form.review.insuranceSection": "Insurance and Doctor",
    "form.review.note": "Review all information before saving",

    // NEW: Form buttons
    "form.buttons.next": "Next",
    "form.buttons.back": "Back",
    "form.buttons.save": "Save Medical Profile",
    "form.buttons.addId": "Add Identification Document",
    "form.buttons.addIdNote": "Optional: You can add a photo of your identification",

    // NEW: Form genders
    "form.genders.male": "Male",
    "form.genders.female": "Female",
    "form.genders.other": "Other",
    "form.genders.preferNotToSay": "Prefer not to say",

    // NEW: Form relationships
    "form.relationships.spouse": "Spouse",
    "form.relationships.parent": "Parent",
    "form.relationships.child": "Child",
    "form.relationships.sibling": "Sibling",
    "form.relationships.friend": "Friend",
    "form.relationships.other": "Other",

    // NEW: Form validation
    "form.validation.required": "This field is required",
    "form.validation.minLength": "Must be at least {min} characters",
    "form.validation.lettersOnly": "Only letters allowed",
    "form.validation.invalidEmail": "Invalid email",
    "form.validation.invalidPhone": "Invalid phone number (minimum 10 digits)",
    "form.validation.invalidDate": "Invalid date",

    // Legal - Terms & Conditions
    "legal.terms.title": "Terms & Conditions",
    "legal.terms.version": "Version 1.0",
    "legal.terms.lastUpdated": "Last Updated: January 2024",
    "legal.terms.effectiveDate": "Effective Date",
    "legal.terms.backButton": "Back",
    "legal.terms.footer": "By using MedBridge, you acknowledge that you have read, understood, and agree to be bound by these Terms & Conditions.",
    "legal.terms.section1.title": "1. Acceptance of Terms",
    "legal.terms.section1.content": "By accessing and using MedBridge, you accept and agree to be bound by these Terms & Conditions. If you do not agree to these terms, please do not use this application.",
    "legal.terms.section2.title": "2. Description of Service",
    "legal.terms.section2.content": "MedBridge is a personal medical information management tool that allows you to store and share your medical data locally on your device. The application generates medical reports and emergency cards for personal use only.",
    "legal.terms.section3.title": "3. No Medical Advice",
    "legal.terms.section3.content": "MedBridge does NOT provide medical advice, diagnosis, or treatment. This application is an informational tool only and does not replace professional medical care. Always seek the advice of qualified healthcare providers with any questions you may have regarding medical conditions.",
    "legal.terms.section4.title": "4. Personal Use Only",
    "legal.terms.section4.content": "This application is intended for personal, non-commercial use only. You may not use MedBridge for any commercial purpose or in any way that violates any applicable laws or regulations.",
    "legal.terms.section5.title": "5. User Responsibility",
    "legal.terms.section5.content": "You are solely responsible for the accuracy and completeness of the medical information you enter into MedBridge. You are also responsible for determining when and with whom to share your medical information. We strongly recommend reviewing your information regularly and keeping it up to date.",
    "legal.terms.section6.title": "6. Data Storage",
    "legal.terms.section6.content": "Your medical data is stored locally on your device. Only identification photos may be uploaded to secure cloud storage. You are responsible for backing up your data and maintaining the security of your device.",
    "legal.terms.section7.title": "7. Limitation of Liability",
    "legal.terms.section7.content": "MedBridge is provided 'as-is' without any warranties, express or implied. We shall not be liable for any damages arising from the use or inability to use this application, including but not limited to direct, indirect, incidental, or consequential damages.",
    "legal.terms.section8.title": "8. No Guarantee of Accuracy",
    "legal.terms.section8.content": "We do not guarantee that the application will be error-free, uninterrupted, or free from viruses or other harmful components. We are not responsible for any errors or omissions in the content you create or store.",
    "legal.terms.section9.title": "9. Emergency Use",
    "legal.terms.section9.content": "While MedBridge is designed to facilitate emergency medical information access, we cannot guarantee that emergency responders will be able to access or rely on the information stored in the application. Always carry traditional forms of medical identification as backup.",
    "legal.terms.section10.title": "10. Modifications to Terms",
    "legal.terms.section10.content": "We reserve the right to modify these Terms & Conditions at any time. When we make changes, we will update the version number and effective date. Continued use of the application after changes constitutes acceptance of the new terms.",
    "legal.terms.section11.title": "11. Termination",
    "legal.terms.section11.content": "You may stop using MedBridge at any time. Simply delete the application and any associated data from your device. These Terms & Conditions will continue to apply to any use you made of the application before termination.",
    "legal.terms.section12.title": "12. Governing Law",
    "legal.terms.section12.content": "These Terms & Conditions shall be governed by and construed in accordance with applicable local laws, without regard to conflict of law principles.",
    "legal.terms.section13.title": "13. Contact",
    "legal.terms.section13.content": "If you have any questions about these Terms & Conditions, please contact us through the application's support channels.",

    // Legal - Privacy Policy
    "legal.privacy.title": "Privacy Policy",
    "legal.privacy.version": "Version 1.0",
    "legal.privacy.lastUpdated": "Last Updated: January 2024",
    "legal.privacy.effectiveDate": "Effective Date",
    "legal.privacy.backButton": "Back",
    "legal.privacy.footer": "By using MedBridge, you acknowledge that you have read, understood, and agree to this Privacy Policy.",
    "legal.privacy.section1.title": "1. Introduction",
    "legal.privacy.section1.content": "This Privacy Policy explains how MedBridge handles your personal and medical information. We are committed to protecting your privacy and giving you control over your data.",
    "legal.privacy.section2.title": "2. Information We Collect",
    "legal.privacy.section2.content": "MedBridge allows you to store personal and medical information including: name, date of birth, medical history, medications, allergies, emergency contacts, and identification photos. This information is entered voluntarily by you.",
    "legal.privacy.section3.title": "3. How We Store Your Data",
    "legal.privacy.section3.content": "Your medical data is stored locally on your device using browser storage mechanisms. We do NOT store your medical information on our servers or in the cloud. Only identification photos may be uploaded to secure cloud storage for backup purposes.",
    "legal.privacy.section4.title": "4. No Cloud Storage of Medical Data",
    "legal.privacy.section4.content": "Your medical information (diagnoses, medications, allergies, etc.) never leaves your device. It is not transmitted to any server, cloud service, or third party. This data exists only on your local device.",
    "legal.privacy.section5.title": "5. Identification Photos",
    "legal.privacy.section5.content": "If you choose to upload an identification photo, it may be stored in secure cloud storage. This is optional and only for the purpose of identity verification in emergency situations.",
    "legal.privacy.section6.title": "6. No Analytics or Tracking",
    "legal.privacy.section6.content": "We do NOT track, analyze, or monitor your medical data usage. We do not use cookies, analytics services, or tracking pixels to collect information about how you use your medical information.",
    "legal.privacy.section7.title": "7. No Selling or Sharing",
    "legal.privacy.section7.content": "We will NEVER sell, rent, or share your personal or medical information with third parties for marketing or commercial purposes. Your data is yours and yours alone.",
    "legal.privacy.section8.title": "8. User Control",
    "legal.privacy.section8.content": "You have complete control over your data. You can edit, delete, or export your information at any time. Since data is stored locally, deleting the application or clearing browser data will permanently remove your information.",
    "legal.privacy.section9.title": "9. Data Security",
    "legal.privacy.section9.content": "While we implement security measures, the security of your data ultimately depends on the security of your device. We recommend: using device passwords, enabling encryption, keeping your device updated, and being cautious about who has physical access to your device.",
    "legal.privacy.section10.title": "10. Third-Party Services",
    "legal.privacy.section10.content": "MedBridge may use third-party services for cloud storage of identification photos. These services have their own privacy policies. We choose reputable providers and limit data sharing to only what is necessary.",
    "legal.privacy.section11.title": "11. Children's Privacy",
    "legal.privacy.section11.content": "MedBridge can be used to store medical information for users of all ages, including children. Parents or legal guardians are responsible for managing medical information for minors.",
    "legal.privacy.section12.title": "12. Changes to Privacy Policy",
    "legal.privacy.section12.content": "We may update this Privacy Policy from time to time. When we do, we will update the version number and effective date. Continued use of the application constitutes acceptance of the updated policy.",
    "legal.privacy.section13.title": "13. Your Rights",
    "legal.privacy.section13.content": "You have the right to: access your data, correct inaccurate data, delete your data, export your data, and control who sees your information. All of these actions can be performed directly within the application.",
    "legal.privacy.section14.title": "14. Contact",
    "legal.privacy.section14.content": "If you have questions about this Privacy Policy or how we handle your information, please contact us through the application's support channels.",

    // Legal Acceptance Modal
    "legal.modal.title": "Terms & Privacy Notice",
    "legal.modal.description": "Legal acceptance required to use the application",
    "legal.modal.summary1": "This app allows you to store and share medical information for personal use only.",
    "legal.modal.summary2": "Your medical data is stored locally on your device. Only an identification photo may be uploaded to secure cloud storage.",
    "legal.modal.summary3": "This app does not provide medical advice and does not replace professional medical care.",
    "legal.modal.readTerms": "Read Terms & Conditions",
    "legal.modal.readPrivacy": "Read Privacy Policy",
    "legal.modal.checkbox": "I have read and agree to the Terms & Conditions and Privacy Policy",
    "legal.modal.acceptButton": "Accept & Continue",
    "legal.modal.accept": "Accept & Continue",
    "legal.modal.back": "Back"
  },
  pt: {
    // Hero Section
    "hero.title": "Sua Informação Médica,",
    "hero.titleHighlight": "Sempre Com Você",
    "hero.subtitle": "Acesse seu histórico médico, alergias e contatos de emergência a qualquer momento. Um código QR que pode salvar sua vida.",
    "hero.cta": "Criar Seu Medical ID",
    "hero.viewCard": "Ver Seu Medical Card",
    "hero.learnMore": "Saiba Mais",

    // Problem Section
    "problem.title": "Isso já aconteceu com você?",
    "problem.item1": "Emergências médicas em países estrangeiros onde você não fala o idioma",
    "problem.item2": "Sem acesso à internet quando mais precisa",
    "problem.item3": "Perda de tempo crítico tentando comunicar seu histórico médico",

    // Solution Section
    "solution.title": "MedBridge é sua solução",
    "solution.item1": "Cartão médico digital segura com todas as suas informações",
    "solution.item2": "Funciona sem internet - acesso offline garantido",
    "solution.item3": "Gera relatórios médicos em PDF instantaneamente",
    "solution.item4": "Tradução automática para múltiplos idiomas",

    // Access Section
    "access.title": "Acesso em Emergências",
    "access.subtitle": "Projetado para socorristas. Escaneie o QR e obtenha informações vitais instantaneamente, mesmo offline.",
    "access.cta": "Criar Seu Medical ID",
    "access.viewCard": "Ver Seu Medical Card",

    // Features Section
    "features.title": "Principais Recursos",
    "features.subtitle": "Tudo o que você precisa para sua segurança médica",
    "features.item1": "Perfil médico pessoal",
    "features.item2": "Tipo sanguíneo e alergias",
    "features.item3": "Contatos de emergência",
    "features.item4": "Informações do médico",
    "features.item5": "Cartão médico pronto para emergências",
    "features.item6": "Compartilhe relatório médico por email quando precisar",

    // Privacy Section
    "privacy.title": "Seus dados permanecem privados.",
    "privacy.subtitle": "Você decide quem vê suas informações",
    "privacy.point1": "Sem armazenamento na nuvem",
    "privacy.point2": "Sem servidores",
    "privacy.point3": "Dados salvos localmente no seu dispositivo",
    "privacy.point4": "Você controla quando compartilhar",

    // Form Steps
    "form.step": "Passo",
    "form.of": "de",
    
    // Form Sections
    "form.sections.personalInfo": "Informação Pessoal",
    "form.sections.medicalHistory": "Histórico Médico",
    "form.sections.emergencyContact": "Contato de Emergência",
    "form.sections.insurance": "Seguro Médico",
    "form.sections.additionalInfo": "Informação Adicional",
    
    // Form Fields
    "form.fields.firstName": "Primeiro Nome",
    "form.fields.lastName": "Sobrenome",
    "form.fields.dateOfBirth": "Data de Nascimento",
    "form.fields.gender": "Gênero",
    "form.fields.phoneNumber": "Telefone",
    "form.fields.email": "Email",
    "form.fields.address": "Endereço",
    "form.fields.city": "Cidade",
    "form.fields.state": "Estado/Província",
    "form.fields.zipCode": "Código Postal",
    "form.fields.country": "País",
    "form.fields.bloodType": "Tipo Sanguíneo",
    "form.fields.allergies": "Alergias",
    "form.fields.currentMedications": "Medicamentos Atuais",
    "form.fields.medicalConditions": "Condições Médicas",
    "form.fields.chronicIllnesses": "Doenças Crônicas",
    "form.fields.pastSurgeries": "Cirurgias Anteriores",
    "form.fields.disabilities": "Deficiências",
    "form.fields.emergencyContactName": "Nome do Contato",
    "form.fields.emergencyContactPhone": "Telefone do Contato",
    "form.fields.emergencyContactEmail": "Email do Contato",
    "form.fields.emergencyContactRelationship": "Relacionamento",
    "form.fields.insuranceProvider": "Provedor de Seguro",
    "form.fields.policyNumber": "Número da Apólice",
    "form.fields.groupNumber": "Número do Grupo",
    "form.fields.insurancePhone": "Telefone do Seguro",
    "form.fields.primaryPhysicianName": "Nome do Médico",
    "form.fields.primaryPhysicianPhone": "Telefone do Médico",
    "form.fields.primaryPhysicianClinic": "Clínica/Hospital",
    "form.fields.specialInstructions": "Instruções Especiais",
    "form.fields.additionalNotes": "Notas Adicionais",

    // Form Personal Information
    "form.personal.title": "Informação Pessoal",
    "form.personal.fullName": "Nome Completo",
    "form.personal.fullNamePlaceholder": "Digite seu nome completo",
    "form.personal.dateOfBirth": "Data de Nascimento",
    "form.personal.nationality": "Nacionalidade",
    "form.personal.nationalityPlaceholder": "Digite sua nacionalidade",
    "form.personal.gender": "Estado Civil",
    "form.personal.genderPlaceholder": "Selecione estado civil",
    "form.personal.passportNumber": "Número do Passaporte",
    "form.personal.passportNumberPlaceholder": "Digite número do passaporte",
    "form.personal.address": "Endereço Permanente",
    "form.personal.addressPlaceholder": "Digite seu endereço",
    "form.personal.bloodType": "Tipo Sanguíneo",
    "form.personal.bloodTypePlaceholder": "Selecione seu tipo sanguíneo",

    // Form Medical History
    "form.history.title": "Histórico Médico",
    "form.history.chronicConditions": "Diagnósticos Anteriores",
    "form.history.chronicConditionsPlaceholder": "Digite diagnósticos anteriores",
    "form.history.currentMedications": "Medicamentos Atuais",
    "form.history.currentMedicationsPlaceholder": "Digite medicamentos atuais",
    "form.history.previousSurgeries": "Cirurgias Anteriores",
    "form.history.previousSurgeriesPlaceholder": "Digite cirurgias anteriores",
    "form.history.allergies": "Alergias a Medicamentos",
    "form.history.allergiesPlaceholder": "Digite alergias a medicamentos",

    // Form Emergency Contacts
    "form.emergency.title": "Contato de Emergência Principal",
    "form.emergency.name": "Nome Completo",
    "form.emergency.namePlaceholder": "Digite nome completo",
    "form.emergency.phone": "Telefone Celular",
    "form.emergency.phonePlaceholder": "Digite número de telefone",
    "form.emergency.email": "Email",
    "form.emergency.emailPlaceholder": "Digite email",

    // Form Insurance & Doctor
    "form.insurance.primaryPhysician": "Médico de Família",
    "form.insurance.primaryPhysicianPlaceholder": "Nome do médico",
    "form.insurance.physicianPhone": "Telefone do Médico",
    "form.insurance.physicianPhonePlaceholder": "Telefone do médico",

    // Form Additional
    "form.additional.advanceDirectives": "Aceita Transfusões de Sangue?",

    // Common
    "common.optional": "(Opcional)",
    "common.yes": "Sim",
    "common.no": "Não",
    "common.next": "Próximo",
    "common.back": "Voltar",
    "common.unknown": "Não especificado",
    "common.notes": "Notas",

    // Validation
    "validation.required": "Este campo é obrigatório",
    "validation.invalidEmail": "Email inválido",
    "validation.invalidPhone": "Número de telefone inválido",
    "validation.invalidDate": "Data inválida",

    // Card
    "card.noProfile": "Sem Perfil Médico",
    "card.createProfilePrompt": "Crie seu perfil médico para acessar seu cartão de emergência",
    "card.createProfile": "Criar Perfil Médico",
    "card.name": "Nome",
    "card.dob": "Data de Nascimento",
    "card.bloodType": "Tipo Sanguíneo",
    "card.allergies": "Alergias",
    "card.currentMedications": "Medicamentos Atuais",
    "card.medicalConditions": "Condições Médicas",
    "card.current": "Atuais",
    "card.chronic": "Crônicas",
    "card.surgicalHistory": "Histórico Cirúrgico",
    "card.emergencyContact": "Contato de Emergência",
    "card.primaryPhysician": "Médico de Família",
    "card.specialInstructions": "Instruções Especiais",
    "card.additionalNotes": "Notas Adicionais",
    "card.phone": "Telefone",
    "card.none": "Nenhuma",
    "card.notSpecified": "Não especificado",
    "card.editInfo": "Editar Informação",
    "card.shareProfile": "Compartilhar Perfil Médico",
    "card.viewId": "Ver Identificação",
    "card.generating": "Gerando...",
    "card.shareTitle": "Relatório Médico MedBridge",
    "card.shareText": "Perfil médico e informação de emergência",
    "card.shareError": "Erro ao compartilhar. Por favor tente novamente.",

    // ID Section
    "id.title": "Personal ID",
    "id.subtitle": "Carregue uma foto da sua identificação oficial",
    "id.uploadDocument": "Carregar documento de identificação",
    "id.invalidFileType": "Por favor, carregue uma imagem válida (JPG, PNG, etc.)",
    "id.fileTooLarge": "Arquivo muito grande. Máximo 3MB permitido.",
    "id.processingError": "Erro ao processar imagem. Tente novamente.",
    "id.tapToUpload": "Toque para carregar foto",
    "id.dragAndDrop": "ou arraste e solte aqui",
    "id.useCamera": "Usar câmera",
    "id.chooseFromGallery": "Escolher da galeria",
    "id.fileRequirements": "JPG, PNG até 3MB",
    "id.preview": "Visualização",
    "id.remove": "Remover",
    "id.replacePhoto": "Substituir foto",
    "id.save": "Salvar e continuar",
    "id.saveSuccess": "Foto salva com sucesso!",
    "id.saveError": "Erro ao salvar foto. Tente novamente.",
    "id.note": "Nota",
    "id.noteDescription": "Esta foto é armazenada localmente no seu dispositivo para verificação de identidade em emergencias.",

    // PDF
    "pdf.reportTitle": "Relatório Médico de Emergência",
    "pdf.generatedOn": "Gerado em",
    "pdf.language": "Idioma",
    "pdf.sectionPatient": "INFORMAÇÃO DO PACIENTE",
    "pdf.sectionMedicalBasics": "INFORMAÇÃO MÉDICA BÁSICA",
    "pdf.sectionAllergies": "ALERGIAS",
    "pdf.sectionMedicalHistory": "HISTÓRICO MÉDICO",
    "pdf.sectionEmergencyContact": "CONTATO DE EMERGÊNCIA",
    "pdf.sectionPrimaryPhysician": "MÉDICO PRIMÁRIO",
    "pdf.fullName": "Nome Completo",
    "pdf.dateOfBirth": "Data de Nascimento",
    "pdf.nationality": "Nacionalidade",
    "pdf.bloodType": "Tipo de Sangre",
    "pdf.medicationAllergies": "Alergias a Medicamentos",
    "pdf.currentDiagnoses": "Diagnósticos Atuais",
    "pdf.previousDiagnoses": "Diagnósticos Anteriores",
    "pdf.currentMedications": "Medicamentos Atuais",
    "pdf.surgicalHistory": "Histórico Cirúrgico",
    "pdf.contactName": "Nome do Contato",
    "pdf.mobilePhone": "Telefone Celular",
    "pdf.physicianName": "Nome do Médico",
    "pdf.physicianPhone": "Telefone do Médico",
    "pdf.clinicHospital": "Clínica/Hospital",
    "pdf.noneReported": "Nenhuma reportada",
    "pdf.footerLine1": "Este documento foi gerado localmente pelo paciente.",
    "pdf.footerLine2": "Os dados médicos são armazenados offline no dispositivo.",

    // NEW: Form step titles
    "form.steps.personalInfo": "Informação Pessoal",
    "form.steps.emergencyContact": "Contato de Emergência",
    "form.steps.medicalInfo": "Informação Médica",
    "form.steps.insurance": "Seguro Médico",
    "form.steps.primaryPhysician": "Médico Primário",
    "form.steps.notesConsent": "Notas e Consentimento",
    "form.steps.finalReview": "Revisão Final",

    // NEW: Form placeholders
    "form.placeholders.firstName": "ex: João",
    "form.placeholders.lastName": "ex: Silva Santos",
    "form.placeholders.phone": "+55 11 98765-4321",
    "form.placeholders.email": "exemplo@email.com",
    "form.placeholders.address": "Rua Principal, 123",
    "form.placeholders.city": "Cidade",
    "form.placeholders.state": "Estado",
    "form.placeholders.zipCode": "12345-678",
    "form.placeholders.country": "País",
    "form.placeholders.selectGender": "Selecione seu gênero",
    "form.placeholders.selectBloodType": "Selecione tipo sanguíneo",
    "form.placeholders.selectRelationship": "Selecione relacionamento",
    "form.placeholders.fullName": "Nome completo",
    "form.placeholders.insuranceProvider": "Nome da seguradora",
    "form.placeholders.policyNumber": "Número da apólice",
    "form.placeholders.groupNumber": "Número do grupo",
    "form.placeholders.doctorName": "Dr. João Silva",
    "form.placeholders.clinicName": "Nome da clínica ou hospital",
    "form.placeholders.medicalConditions": "Descreva qualquer condição médica atual",
    "form.placeholders.allergies": "Liste todas as suas alergias (medicamentos, alimentos, etc.)",
    "form.placeholders.currentMedications": "Liste todos os medicamentos que está tomando atualmente",
    "form.placeholders.pastSurgeries": "Describa qualquer cirurgia previa",
    "form.placeholders.chronicIllnesses": "Liste qualquer doença crônica",
    "form.placeholders.disabilities": "Descreva qualquer deficiência",
    "form.placeholders.specialInstructions": "Qualquer instrução especial para pessoal médico",
    "form.placeholders.additionalNotes": "Qualquer informação adicional relevante",

    // NEW: Form consent
    "form.consent.title": "Consentimentos",
    "form.consent.treatment": "Consentimiento para Tratamiento",
    "form.consent.treatmentDesc": "Autorizo el tratamiento médico de emergencia",
    "form.consent.shareInfo": "Compartir Información Médica",
    "form.consent.shareInfoDesc": "Autorizo compartir mi información con personal médico",

    // NEW: Form review section
    "form.review.title": "Revisão Final",
    "form.review.subtitle": "Revise toda la información antes de guardar",
    "form.review.personalInfoSection": "Información Personal",
    "form.review.emergencyContactSection": "Contacto de Emergencia",
    "form.review.medicalInfoSection": "Información Médica",
    "form.review.insuranceSection": "Seguro y Doctor",
    "form.review.note": "Revise toda la información antes de guardar",

    // NEW: Form buttons
    "form.buttons.next": "Próximo",
    "form.buttons.back": "Voltar",
    "form.buttons.save": "Salvar Perfil Médico",
    "form.buttons.addId": "Adicionar Documento de Identificação",
    "form.buttons.addIdNote": "Opcional: Você pode adicionar uma foto da sua identificação",

    // NEW: Form genders
    "form.genders.male": "Masculino",
    "form.genders.female": "Feminino",
    "form.genders.other": "Outro",
    "form.genders.preferNotToSay": "Prefiro não dizer",

    // NEW: Form relationships
    "form.relationships.spouse": "Cônjuge",
    "form.relationships.parent": "Pai/Mãe",
    "form.relationships.child": "Filho/a",
    "form.relationships.sibling": "Irmão/ã",
    "form.relationships.friend": "Amigo/a",
    "form.relationships.other": "Outro",

    // NEW: Form validation
    "form.validation.required": "Este campo é obrigatório",
    "form.validation.minLength": "Deve ter pelo menos {min} caracteres",
    "form.validation.lettersOnly": "Apenas letras permitidas",
    "form.validation.invalidEmail": "Email inválido",
    "form.validation.invalidPhone": "Número de telefone inválido (mínimo 10 dígitos)",
    "form.validation.invalidDate": "Data inválida",

    // Legal - Terms & Conditions
    "legal.terms.title": "Termos & Condições",
    "legal.terms.version": "Versão 1.0",
    "legal.terms.lastUpdated": "Última Atualização: Janeiro 2024",
    "legal.terms.effectiveDate": "Data Efetiva",
    "legal.terms.backButton": "Voltar",
    "legal.terms.footer": "Ao usar o MedBridge, você reconhece que leu, entendeu e concorda em estar vinculado a estes Termos & Condições.",
    "legal.terms.section1.title": "1. Aceitação dos Termos",
    "legal.terms.section1.content": "Ao acessar e usar o MedBridge, você aceita e concorda em estar vinculado a estes Termos & Condições. Se você não concorda com estes termos, por favor não use esta aplicação.",
    "legal.terms.section2.title": "2. Descrição do Serviço",
    "legal.terms.section2.content": "MedBridge é uma ferramenta de gerenciamento de informações médicas pessoais que permite armazenar e compartilhar seus dados médicos localmente no seu dispositivo. A aplicação gera relatórios médicos e cartões de emergência apenas para uso pessoal.",
    "legal.terms.section3.title": "3. Sem Aconselhamento Médico",
    "legal.terms.section3.content": "MedBridge NÃO fornece aconselhamento, diagnóstico ou tratamento médico. Esta aplicação é apenas uma ferramenta informativa e não substitui cuidados médicos profissionais. Sempre procure o conselho de profissionais de saúde qualificados com quaisquer dúvidas sobre condições médicas.",
    "legal.terms.section4.title": "4. Uso Pessoal Apenas",
    "legal.terms.section4.content": "Esta aplicação é destinada apenas para uso pessoal e não comercial. Você não pode usar o MedBridge para qualquer propósito comercial ou de qualquer forma que viole leis ou regulamentos aplicáveis.",
    "legal.terms.section5.title": "5. Responsabilidade do Usuário",
    "legal.terms.section5.content": "Você é o único responsável pela precisão e completude das informações médicas que você insere no MedBridge. Você também é responsável por determinar quando e com quem compartilhar suas informações médicas. Recomendamos fortemente revisar suas informações regularmente e mantê-las atualizadas.",
    "legal.terms.section6.title": "6. Armazenamento de Dados",
    "legal.terms.section6.content": "Seus dados médicos são armazenados localmente no seu dispositivo. Apenas fotos de identificação podem ser enviadas para armazenamento seguro na nuvem. Você é responsável por fazer backup dos seus dados e manter a segurança do seu dispositivo.",
    "legal.terms.section7.title": "7. Limitação de Responsabilidade",
    "legal.terms.section7.content": "MedBridge é fornecido 'como está' sem quaisquer garantias, expressas ou implícitas. Não seremos responsáveis por quaisquer danos decorrentes do uso ou incapacidade de usar esta aplicação, incluindo mas não limitado a danos diretos, indiretos, incidentais ou consequenciais.",
    "legal.terms.section8.title": "8. Sem Garantia de Precisão",
    "legal.terms.section8.content": "Não garantimos que a aplicação estará livre de erros, ininterrupta ou livre de vírus ou outros componentes prejudiciais. Não somos responsáveis por quaisquer erros ou omissões no conteúdo que você cria ou armazena.",
    "legal.terms.section9.title": "9. Uso em Emergências",
    "legal.terms.section9.content": "Embora o MedBridge seja projetado para facilitar o acesso a informações médicas de emergência, não podemos garantir que os socorristas serão capazes de acessar ou confiar nas informações armazenadas na aplicação. Sempre carregue formas tradicionais de identificação médica como backup.",
    "legal.terms.section10.title": "10. Modificações dos Termos",
    "legal.terms.section10.content": "Reservamos o direito de modificar estes Termos & Condições a qualquer momento. Quando fizermos alterações, atualizaremos o número da versão e a data efetiva. O uso continuado da aplicação após as alterações constitui aceitação dos novos termos.",
    "legal.terms.section11.title": "11. Término",
    "legal.terms.section11.content": "Você pode parar de usar o MedBridge a qualquer momento. Simplesmente delete a aplicação e quaisquer dados associados do seu dispositivo. Estes Termos & Condições continuarão a aplicar-se a qualquer uso que você fez da aplicação antes do término.",
    "legal.terms.section12.title": "12. Lei Aplicável",
    "legal.terms.section12.content": "Estes Termos & Condições serão regidos e interpretados de acordo com as leis locais aplicáveis, sem considerar princípios de conflito de leis.",
    "legal.terms.section13.title": "13. Contato",
    "legal.terms.section13.content": "Se você tiver alguma dúvida sobre estes Termos & Condições, entre em contato conosco através dos canais de suporte da aplicação.",

    // Legal - Privacy Policy
    "legal.privacy.title": "Política de Privacidade",
    "legal.privacy.version": "Versão 1.0",
    "legal.privacy.lastUpdated": "Última Atualização: Janeiro 2024",
    "legal.privacy.effectiveDate": "Data Efetiva",
    "legal.privacy.backButton": "Voltar",
    "legal.privacy.footer": "Ao usar o MedBridge, você reconhece que leu, entendeu e concorda com esta Política de Privacidade.",
    "legal.privacy.section1.title": "1. Introdução",
    "legal.privacy.section1.content": "Esta Política de Privacidade explica como o MedBridge lida com suas informações pessoais e médicas. Estamos comprometidos em proteger sua privacidade e dar-lhe controle sobre seus dados.",
    "legal.privacy.section2.title": "2. Informações que Coletamos",
    "legal.privacy.section2.content": "MedBridge permite que você armazene informações pessoais e médicas incluindo: nome, data de nascimento, histórico médico, medicamentos, alergias, contatos de emergência e fotos de identificação. Estas informações são inseridas voluntariamente por você.",
    "legal.privacy.section3.title": "3. Como Armazenamos Seus Dados",
    "legal.privacy.section3.content": "Seus dados médicos são armazenados localmente no seu dispositivo usando mecanismos de armazenamento do navegador. NÃO armazenamos suas informações médicas em nossos servidores ou na nuvem. Apenas fotos de identificação podem ser enviadas para armazenamento seguro na nuvem para fins de backup.",
    "legal.privacy.section4.title": "4. Sem Armazenamento de Dados Médicos na Nuvem",
    "legal.privacy.section4.content": "Suas informações médicas (diagnósticos, medicamentos, alergias, etc.) nunca saem do seu dispositivo. Não são transmitidas para nenhum servidor, serviço na nuvem ou terceiros. Estes dados existem apenas no seu dispositivo local.",
    "legal.privacy.section5.title": "5. Fotos de Identificação",
    "legal.privacy.section5.content": "Se você optar por enviar uma foto de identificação, ela pode ser armazenada em armazenamento seguro na nuvem. Isto é opcional e apenas para fins de verificação de identidade em situações de emergência.",
    "legal.privacy.section6.title": "6. Sem Analytics ou Rastreamento",
    "legal.privacy.section6.content": "NÃO rastreamos, analisamos ou monitoramos o uso dos seus dados médicos. Não usamos cookies, serviços de analytics ou pixels de rastreamento para coletar informações sobre como você usa suas informações médicas.",
    "legal.privacy.section7.title": "7. Sem Venda ou Compartilhamento",
    "legal.privacy.section7.content": "NUNCA venderemos, alugaremos ou compartilharemos suas informações pessoais ou médicas com terceiros para fins de marketing ou comerciais. Seus dados são seus e apenas seus.",
    "legal.privacy.section8.title": "8. Controle do Usuário",
    "legal.privacy.section8.content": "Você tem controle completo sobre seus dados. Você pode editar, deletar ou exportar suas informações a qualquer momento. Como os dados são armazenados localmente, deletar a aplicação ou limpar os dados do navegador removerá permanentemente suas informações.",
    "legal.privacy.section9.title": "9. Segurança de Dados",
    "legal.privacy.section9.content": "Embora implementemos medidas de segurança, a segurança dos seus dados depende em última análise da segurança do seu dispositivo. Recomendamos: usar senhas no dispositivo, habilitar criptografia, manter seu dispositivo atualizado e ter cuidado sobre quem tem acesso físico ao seu dispositivo.",
    "legal.privacy.section10.title": "10. Serviços de Terceiros",
    "legal.privacy.section10.content": "MedBridge pode usar serviços de terceiros para armazenamento na nuvem de fotos de identificação. Estes serviços têm suas próprias políticas de privacidade. Escolhemos provedores respeitáveis e limitamos o compartilhamento de dados apenas ao necessário.",
    "legal.privacy.section11.title": "11. Privacidade de Crianças",
    "legal.privacy.section11.content": "MedBridge pode ser usado para armazenar informações médicas de usuários de todas as idades, incluindo crianças. Pais ou tutores legais são responsáveis por gerenciar informações médicas de menores.",
    "legal.privacy.section12.title": "12. Alterações na Política de Privacidade",
    "legal.privacy.section12.content": "Podemos atualizar esta Política de Privacidade de tempos em tempos. Quando o fizermos, atualizaremos o número da versão e a data efetiva. O uso continuado da aplicação constitui aceitação da política atualizada.",
    "legal.privacy.section13.title": "13. Seus Direitos",
    "legal.privacy.section13.content": "Você tem o direito de: acessar seus dados, corrigir dados imprecisos, deletar seus dados, exportar seus dados e controlar quem vê suas informações. Todas essas ações podem ser realizadas diretamente dentro da aplicação.",
    "legal.privacy.section14.title": "14. Contato",
    "legal.privacy.section14.content": "Se você tiver dúvidas sobre esta Política de Privacidade ou como lidamos com suas informações, entre em contato conosco através dos canais de suporte da aplicação.",

    // Legal Acceptance Modal
    "legal.modal.title": "Aviso de Termos & Privacidade",
    "legal.modal.description": "Aceitação legal necessária para usar a aplicação",
    "legal.modal.summary1": "Esta aplicação permite armazenar e compartilhar informações médicas apenas para uso pessoal.",
    "legal.modal.summary2": "Seus dados médicos são armazenados localmente no seu dispositivo. Apenas uma foto de identificação pode ser enviada para armazenamento seguro na nuvem.",
    "legal.modal.summary3": "Esta aplicação não fornece aconselhamento médico e não substitui cuidados médicos profissionais.",
    "legal.modal.readTerms": "Ler Termos & Condições",
    "legal.modal.readPrivacy": "Ler Política de Privacidade",
    "legal.modal.checkbox": "Li e concordo com os Termos & Condições e Política de Privacidade",
    "legal.modal.acceptButton": "Aceitar & Continuar",
    "legal.modal.accept": "Aceitar & Continuar",
    "legal.modal.back": "Voltar"
  }
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [language, setLanguageState] = useState<Language>("es");
  const [isLoaded, setIsLoaded] = useState(false);

  useEffect(() => {
    const savedLanguage = localStorage.getItem("medbridge-language") as Language;
    if (savedLanguage && ["es", "en", "pt"].includes(savedLanguage)) {
      setLanguageState(savedLanguage);
    }
    setIsLoaded(true);
  }, []);

  const setLanguage = (lang: Language) => {
    setLanguageState(lang);
    if (typeof window !== "undefined") {
      localStorage.setItem("medbridge-language", lang);
    }
  };

  const t = (key: string): string => {
    return translations[language]?.[key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t, isLoaded }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error("useLanguage must be used within a LanguageProvider");
  }
  return context;
}