import React, { createContext, useContext, useState, useEffect, ReactNode } from "react";

type Language = "es" | "en" | "pt";

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const translations: Record<Language, Record<string, string>> = {
  es: {
    // Hero Section
    "hero.title": "Tu Información Médica,",
    "hero.titleHighlight": "Siempre Contigo",
    "hero.subtitle": "Accede a tu historial médico, alergias y contactos de emergencia en cualquier momento. Un código QR que puede salvar tu vida.",
    "hero.cta": "Crea tu Medical ID",
    "hero.viewCard": "Ver tu Medical Card",
    "hero.learnMore": "Conocer Más",

    // Access Section
    "access.title": "Acceso en Emergencias",
    "access.subtitle": "Diseñado para primeros auxilios. Escanea el QR y obtén información vital al instante, incluso sin conexión a internet.",
    "access.cta": "Crea tu Medical ID",
    "access.viewCard": "Ver tu Medical Card",

    // Features Section
    "features.title": "Características Principales",
    "features.subtitle": "Todo lo que necesitas para tu seguridad médica",
    "features.secure": "100% Seguro",
    "features.secureDesc": "Tus datos están encriptados y bajo tu control total.",
    "features.fast": "Acceso Rápido",
    "features.fastDesc": "Información vital disponible en segundos mediante QR.",
    "features.accessible": "Siempre Disponible",
    "features.accessibleDesc": "Funciona en cualquier dispositivo, sin instalar apps.",

    // Privacy Section
    "privacy.title": "Tu Privacidad es Primero",
    "privacy.subtitle": "Tú decides quién ve tu información",
    "privacy.local": "Almacenamiento Local",
    "privacy.localDesc": "Los datos viven en tu dispositivo, no en la nube.",
    "privacy.control": "Control Total",
    "privacy.controlDesc": "Edita o borra tu información cuando quieras.",

    // Form
    "form.title": "Tu Ficha Médica",
    "form.subtitle": "Completa tus datos para generar tu tarjeta",
    "form.personal": "Datos Personales",
    "form.medical": "Datos Médicos",
    "form.contacts": "Contactos de Emergencia",
    "form.save": "Guardar Información",
    
    // PDF/Card
    "card.title": "Medical ID",
    "card.scan": "Escanear para ver detalles completos",
    "pdf.generated": "Generado por MedBridge",
    "pdf.footerLine1": "En caso de emergencia, escanee el código QR.",
    "pdf.footerLine2": "Los datos médicos se almacenan localmente.",
    "pdf.button": "Generar PDF"
  },
  en: {
    // Hero Section
    "hero.title": "Your Medical Information,",
    "hero.titleHighlight": "Always With You",
    "hero.subtitle": "Access your medical history, allergies, and emergency contacts anytime. A QR code that can save your life.",
    "hero.cta": "Create Your Medical ID",
    "hero.viewCard": "View Your Medical Card",
    "hero.learnMore": "Learn More",

    // Access Section
    "access.title": "Emergency Access",
    "access.subtitle": "Designed for first responders. Scan the QR and get vital information instantly, even offline.",
    "access.cta": "Create Your Medical ID",
    "access.viewCard": "View Your Medical Card",

    // Features Section
    "features.title": "Key Features",
    "features.subtitle": "Everything you need for your medical safety",
    "features.secure": "100% Secure",
    "features.secureDesc": "Your data is encrypted and under your total control.",
    "features.fast": "Fast Access",
    "features.fastDesc": "Vital information available in seconds via QR.",
    "features.accessible": "Always Available",
    "features.accessibleDesc": "Works on any device, no app installation needed.",

    // Privacy Section
    "privacy.title": "Your Privacy First",
    "privacy.subtitle": "You decide who sees your information",
    "privacy.local": "Local Storage",
    "privacy.localDesc": "Data lives on your device, not in the cloud.",
    "privacy.control": "Total Control",
    "privacy.controlDesc": "Edit or delete your information whenever you want.",

    // Form
    "form.title": "Your Medical Record",
    "form.subtitle": "Fill in your details to generate your card",
    "form.personal": "Personal Details",
    "form.medical": "Medical Data",
    "form.contacts": "Emergency Contacts",
    "form.save": "Save Information",

    // PDF/Card
    "card.title": "Medical ID",
    "card.scan": "Scan to view full details",
    "pdf.generated": "Generated by MedBridge",
    "pdf.footerLine1": "In case of emergency, scan the QR code.",
    "pdf.footerLine2": "Medical data is stored locally.",
    "pdf.button": "Generate PDF"
  },
  pt: {
    // Hero Section
    "hero.title": "Sua Informação Médica,",
    "hero.titleHighlight": "Sempre Com Você",
    "hero.subtitle": "Acesse seu histórico médico, alergias e contatos de emergência a qualquer momento. Um código QR que pode salvar sua vida.",
    "hero.cta": "Criar Seu Medical ID",
    "hero.viewCard": "Ver Seu Medical Card",
    "hero.learnMore": "Saiba Mais",

    // Access Section
    "access.title": "Acesso em Emergências",
    "access.subtitle": "Projetado para socorristas. Escaneie o QR e obtenha informações vitais instantaneamente, mesmo offline.",
    "access.cta": "Criar Seu Medical ID",
    "access.viewCard": "Ver Seu Medical Card",

    // Features Section
    "features.title": "Principais Recursos",
    "features.subtitle": "Tudo o que você precisa para sua segurança médica",
    "features.secure": "100% Seguro",
    "features.secureDesc": "Seus dados são criptografados e estão sob seu controle total.",
    "features.fast": "Acesso Rápido",
    "features.fastDesc": "Informações vitais disponíveis em segundos via QR.",
    "features.accessible": "Sempre Disponível",
    "features.accessibleDesc": "Funciona em qualquer dispositivo, sem instalar apps.",

    // Privacy Section
    "privacy.title": "Sua Privacidade em Primeiro Lugar",
    "privacy.subtitle": "Você decide quem vê suas informações",
    "privacy.local": "Armazenamento Local",
    "privacy.localDesc": "Os dados ficam no seu dispositivo, não na nuvem.",
    "privacy.control": "Controle Total",
    "privacy.controlDesc": "Edite ou exclua suas informações quando quiser.",

    // Form
    "form.title": "Sua Ficha Médica",
    "form.subtitle": "Preencha seus dados para gerar seu cartão",
    "form.personal": "Dados Pessoais",
    "form.medical": "Dados Médicos",
    "form.contacts": "Contatos de Emergência",
    "form.save": "Salvar Informações",

    // PDF/Card
    "card.title": "Medical ID",
    "card.scan": "Escaneie para ver detalhes completos",
    "pdf.generated": "Gerado por MedBridge",
    "pdf.footerLine1": "Em caso de emergência, escaneie o código QR.",
    "pdf.footerLine2": "Os dados médicos são armazenados localmente.",
    "pdf.button": "Gerar PDF"
  }
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [language, setLanguageState] = useState<Language>("es");

  useEffect(() => {
    const savedLanguage = localStorage.getItem("medbridge-language") as Language;
    if (savedLanguage && ["es", "en", "pt"].includes(savedLanguage)) {
      setLanguageState(savedLanguage);
    }
  }, []);

  const setLanguage = (lang: Language) => {
    setLanguageState(lang);
    localStorage.setItem("medbridge-language", lang);
  };

  const t = (key: string): string => {
    return translations[language]?.[key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error("useLanguage must be used within a LanguageProvider");
  }
  return context;
}